function BGS_questionnaires = call_BGS_questionnaires
%call_BGS_questions
%This function can call dictionary of Bartoshuk's general sensitivity questionnaires.
%its output is rating_types, and it has 3 substructure.
%stimuli_types : types of stimuli
%rating_types.alltypes : dictionary of rating types
%rating_types.prompts : prompts for each rating type


BGS_questionnaires.prompt_ex = '각 항목에 대해 여러분이 느끼는 정도를 알려주세요.\n아래에 있는 척도를 이용하셔서 여러분이 느끼는 정도에 가장 알맞은 정도를 골라주시길 바랍니다.\n가능한 한 최대한 정확하고 정직하게 답변해주시길 부탁드립니다.';
BGS_questionnaires.prompt_ex = BGS_questionnaires.prompt_ex;

BGS_questionnaires.stimulus_types = ...
    {
    'room_light', '이 방의 빛의 밝기'; ...
    'restaurant_light', '레스토랑의 어두운 빛의 밝기'; ...
    'experienced_brightest_light', '경험해본 가장 밝은 빛의 밝기'; ...
    'whisper_sound', '귓속말의 소리 크기'; ...
    'conversation_sound', '보통 대화의 소리 크기'; ...
    'experienced_loudest_sound', '경험해본 가장 큰 소리의 크기'; ...
    'warm_bread_in_mouth', '입안의 따뜻한 빵의 따뜻함 정도'; ...
    'flower_strongest_scent', '꽃의 가장 강한 향의 정도'; ...
    'coke_sweetness', '콜라의 단맛 정도'; ...
    'celery_bitterness', '셀러리의 쓴맛 정도'; ...
    'experienced_most_salty', '경험해본 가장 짠맛의 정도'; ...
    'experienced_most_sweet', '경험해본 가장 단맛의 정도'; ...
    'experienced_most_sour', '경험해본 가장 신맛의 정도'; ...
    'experienced_most_bitter', '경험해본 가장 쓴맛의 정도'; ...
    'experienced_most_spicy', '경험해본 가장 매운맛의 정도 (예: 청양고추 등)'; ...
    'experienced_strongest_mouthpain', '경험해본 가장 강한 구강 통증 (예: 치통 등)'; ...
    'experienced_strongest_pain', '종류 상관 없이 경험해본 가장 강한 통증'; ...
    'candy_sweetness', '사탕 (단맛의 정도)'};
    %     '종류 상관 없이 경험해본 가장 강한 통증 (통증의 종류를 적어주세요)'
    %     'PROP 종이 (쓴맛의 정도)', ...
BGS_questionnaires.stimulus_types_label = BGS_questionnaires.stimulus_types(:,1);
BGS_questionnaires.stimulus_types_content = BGS_questionnaires.stimulus_types(:,2);

% ********** IMPORTANT NOTE **********
% YOU CAN ADD TYPES AND PROMPTS HERE. "cont_" AND "overall_" ARE IMPORTANT.
% * CRUCIAL: THE ORDER BETWEEN alltypes AND prompts SHOULD BE THE SAME.*

end